[workspace]
authors = ["Scott Henderson <3924836+scottyhq@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "skypilotAzure"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"

[pypi-options]
 prerelease-mode = "allow"

[pypi-dependencies]
skypilot = { version = ">=0.11.1, <0.12", extras = ["azure"] }
